# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        SerBinario\MBCredito\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_PA:          ROLE_USER
        ROLE_ADMIN:       ROLE_PA
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: UserBundle:User }

    firewalls:
         secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /mbcredito
            
    access_control:
        - { path: ^/mbcredito, roles: ROLE_USER }